export const connectData = [
  {
    id: 0,
    name: 'GitHub',
    url: 'https://github.com/zkm',
    width: 24,
    height: 24,
    icon: 'github.svg',
  },
  {
    id: 1,
    name: 'LinkedIn',
    url: 'https://www.linkedin.com/in/zschneider/',
    width: 24,
    height: 24,
    icon: 'linkedin.svg',
  },
  {
    id: 2,
    name: 'Instagram',
    url: 'https://www.instagram.com/zachschneider/',
    width: 24,
    height: 24,
    icon: 'instagram.svg',
  },
  {
    id: 3,
    name: 'Twitter',
    url: 'https://twitter.com/zkm',
    width: 24,
    height: 24,
    icon: 'twitter.svg',
  },
  {
    id: 4,
    name: 'StackOverflow',
    url: 'https://stackoverflow.com/users/461733/zach-schneider',
    width: 18,
    height: 18,
    icon: 'link.svg',
  },
];
